### ISSUE TITLE
Intents not working

### ISSUE THREAD

**Issue by vco1** [traccar/traccar-client#16]
I used to start and stop Traccar through Tasker by sending intents. This is unfortunately no longer working as of version 9.x.

Tasker is also able to open shortcuts. Which could be an alternative to using intents. But no shortcuts are showing for Traccar in Tasker.

**Comment by vco1** [comment]
Thanks. This does open Traccar, but doesn't start or stop (continuous) tracking.

**Comment by tananaev** [comment]
Actually my comment was incorrect. The extra key should be `some unique action key` (literally this with spaces).

I am able to trigger it using this adb command:
```
adb shell am start -n org.traccar.client/.MainActivity -a android.intent.action.RUN --es '"some unique action key"' "start"
```

**Comment by patienttruth** [comment]
If anyone is trying to trigger this from Home Assistant, here is a snippet.

```
action: notify.mobile_app_your_device
data:
  message: command_activity
  data:
    intent_package_name: org.traccar.client
    intent_class_name: org.traccar.client.MainActivity
    intent_action: android.intent.action.RUN
    intent_extras: "some unique action key:start"
```
